[project]
name = "work-force-360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.118.3",
    "python-jose[cryptography]>=3.5.0",
    "uvicorn>=0.37.0",
]
